Implement WebInteractionDelegate
TransfloEngineers/mobile-sdk-ios pull request #3
Opened 2023-08-02 14:38 UTC by vladpcog

**Summary**

- [x] Created `WebInteractionDelegate` protocol, with default empty implementations
- [x] Added delegate logic inside DriveController

2023-08-04 14:02 UTC, iulian-cata-cg requested changes

2023-08-04 14:02 UTC, iulian-cata-cg commented on Sources/GeotabMobileSDK/Classes/Protocols/WebInteractionDelegate.swift
> +    func decidePolicyFor(navigationAction: WKNavigationAction)
I think this needs a small name tweak so it is not creating confusion with the same from WKNavigationDelegate.
Something like "onDecidePolicy"/"decidePolicyCalledFor".

2023-08-07 06:55 UTC, vladpcog commented on Sources/GeotabMobileSDK/Classes/Protocols/WebInteractionDelegate.swift
> +    func decidePolicyFor(navigationAction: WKNavigationAction)
Updated. 👍

2023-08-07 08:42 UTC, iulian-cata-cg approved these changes

2023-08-07 08:45 UTC, merged